### PR TITLE
update api endpoint

### PR DESCRIPTION
**Pull request by paynegreen**
Rework the endpoint

### CODE REVIEW

**Review by tommie24 — COMMENTED** [review]
@paynegreen is the update also done on the transaction repo?

**Comment by paynegreen** [comment]
It was based on the existing tech. Since we're keeping this we can leave us such

**Comment by tommie24** [comment]
We are keeping it to point to the transaction Auth. 
I want to approve this. Just wanted to know if the implementation is done.
They have started using the transaction auth

**Comment by tommie24** [comment]
@paynegreen and @ajibukunoluwa 
Does this still hold?

**Comment by paynegreen** [comment]
I'm out of the loop on how our services interact through Artemis at the moment.

**Pull request closed without merging**
